CREATE TABLE dbexpress.API (
	API_ID INT auto_increment NOT NULL,
	NAME varchar(100) NULL,
	URL varchar(500) NULL,
	CONSTRAINT API_PK PRIMARY KEY (API_ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;
