CREATE TABLE dbforesthealing113.TEAM (
	teamId BIGINT auto_increment NOT NULL,
	team varchar(10) NOT NULL,
	manager varchar(10) NULL,
	phone varchar(100) NULL,
	updateDate DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	saveDate DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT TEAM_PK PRIMARY KEY (teamId)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;
